// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: gamefrontend.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Gamefrontend {
  public static partial class GameFrontendMMService
  {
    static readonly string __ServiceName = "gamefrontend.GameFrontendMMService";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::Gamefrontend.ClientMatchMakingRequest> __Marshaller_gamefrontend_ClientMatchMakingRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Gamefrontend.ClientMatchMakingRequest.Parser));
    static readonly grpc::Marshaller<global::Gamefrontend.GameFrontendResponse> __Marshaller_gamefrontend_GameFrontendResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Gamefrontend.GameFrontendResponse.Parser));

    static readonly grpc::Method<global::Gamefrontend.ClientMatchMakingRequest, global::Gamefrontend.GameFrontendResponse> __Method_FindMatch = new grpc::Method<global::Gamefrontend.ClientMatchMakingRequest, global::Gamefrontend.GameFrontendResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "FindMatch",
        __Marshaller_gamefrontend_ClientMatchMakingRequest,
        __Marshaller_gamefrontend_GameFrontendResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Gamefrontend.GamefrontendReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of GameFrontendMMService</summary>
    [grpc::BindServiceMethod(typeof(GameFrontendMMService), "BindService")]
    public abstract partial class GameFrontendMMServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Gamefrontend.GameFrontendResponse> FindMatch(global::Gamefrontend.ClientMatchMakingRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(GameFrontendMMServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_FindMatch, serviceImpl.FindMatch).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, GameFrontendMMServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_FindMatch, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Gamefrontend.ClientMatchMakingRequest, global::Gamefrontend.GameFrontendResponse>(serviceImpl.FindMatch));
    }

  }
}
#endregion
