// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: gamefrontend.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Gamefrontend {
  public static partial class GameFrontendMMService
  {
    static readonly string __ServiceName = "gamefrontend.GameFrontendMMService";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::Gamefrontend.ClientMatchMakingRequest> __Marshaller_gamefrontend_ClientMatchMakingRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Gamefrontend.ClientMatchMakingRequest.Parser));
    static readonly grpc::Marshaller<global::Gamefrontend.GameFrontendResponse> __Marshaller_gamefrontend_GameFrontendResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Gamefrontend.GameFrontendResponse.Parser));

    static readonly grpc::Method<global::Gamefrontend.ClientMatchMakingRequest, global::Gamefrontend.GameFrontendResponse> __Method_FindMatch = new grpc::Method<global::Gamefrontend.ClientMatchMakingRequest, global::Gamefrontend.GameFrontendResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "FindMatch",
        __Marshaller_gamefrontend_ClientMatchMakingRequest,
        __Marshaller_gamefrontend_GameFrontendResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Gamefrontend.GamefrontendReflection.Descriptor.Services[0]; }
    }

    /// <summary>Client for GameFrontendMMService</summary>
    public partial class GameFrontendMMServiceClient : grpc::ClientBase<GameFrontendMMServiceClient>
    {
      /// <summary>Creates a new client for GameFrontendMMService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public GameFrontendMMServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for GameFrontendMMService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public GameFrontendMMServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected GameFrontendMMServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected GameFrontendMMServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Gamefrontend.GameFrontendResponse FindMatch(global::Gamefrontend.ClientMatchMakingRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return FindMatch(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Gamefrontend.GameFrontendResponse FindMatch(global::Gamefrontend.ClientMatchMakingRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_FindMatch, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Gamefrontend.GameFrontendResponse> FindMatchAsync(global::Gamefrontend.ClientMatchMakingRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return FindMatchAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Gamefrontend.GameFrontendResponse> FindMatchAsync(global::Gamefrontend.ClientMatchMakingRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_FindMatch, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override GameFrontendMMServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new GameFrontendMMServiceClient(configuration);
      }
    }

  }
}
#endregion
